export const Assets = {
  images: {
    homeBackground: require("../images/png/home1.png"),
    homeMainDrone: require("../images/png/droneHome.png"),
    thermalCamera: require("../images/png/captureIcon.png"),
    roboticArm: require("../images/png/robotIcon.png"),
    mpCamera: require("../images/png/camera.png"),
    fiveG: require("../images/png/fiveG.png"),
    groupa: require("../images/png/groupa.png"),
    imageA: require("../images/png/image1.jpg"),
    imageB: require("../images/png/image2.webp"),
    imageC: require("../images/png/image3.jpg"),
    imageE: require("../images/png/image4.jpg"),
    imageF: require("../images/png/image6.jpg"),
    drone: require("../images/png/googleimage.png"),
    contact: require("../images/png/contact-removebg-preview.png"),
    contactHome: require("../images/png/Contact-home.jpg"),
    email: require("../images/png/ic_twotone-email.png"),
    time: require("../images/png/ic_baseline-access-time.png"),
    location: require("../images/png/material-symbols_location-on.png"),
    call: require("../images/png/material-symbols_call.png"),
    contactBackground: require("../images/png/contactbackground.png"),
  },
};
